-- Highest Revenue Region
SELECT REGION, TOTAL_SALES
FROM VW_EXECUTIVE_DASHBOARD
ORDER BY TOTAL_SALES DESC
LIMIT 1;

---Highest Profit Region
SELECT REGION, TOTAL_PROFIT
FROM VW_EXECUTIVE_DASHBOARD
ORDER BY TOTAL_PROFIT DESC
LIMIT 1;

---Most Profitable Product
SELECT PRODUCT_NAME, TOTAL_PROFIT
FROM VW_PRODUCT_PERFORMANCE
ORDER BY TOTAL_PROFIT DESC
LIMIT 1;

---Highest Revenue Category
SELECT CATEGORY, TOTAL_SALES
FROM VW_CATEGORY_PERFORMANCE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
