MERGE INTO FACT_RETAIL_SALES T
USING RETAIL_SALES_STG S
ON T.ORDER_ID = S.ORDER_ID
AND T.PRODUCT_ID = S.PRODUCT_ID

WHEN MATCHED THEN
UPDATE SET
    T.SALES = S.SALES,
    T.PROFIT = S.PROFIT,
    T.QUANTITY = S.QUANTITY

WHEN NOT MATCHED THEN
INSERT (
    ORDER_ID,
    PRODUCT_ID,
    SALES,
    PROFIT,
    QUANTITY
)
VALUES (
    S.ORDER_ID,
    S.PRODUCT_ID,
    S.SALES,
    S.PROFIT,
    S.QUANTITY
);
