CREATE OR REPLACE VIEW STG_RETAIL_SALES AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    SHIP_DATE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    COUNTRY,
    CITY,
    STATE,
    POSTAL_CODE,
    REGION,
    PRODUCT_ID,
    CATEGORY,
    SUB_CATEGORY,
    PRODUCT_NAME,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT
FROM RETAIL_SALES;
