CREATE OR REPLACE PROCEDURE RETAIL_DB.RAW.SP_VALIDATE_RETAIL_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_NULL_CUSTOMER_COUNT NUMBER;
    V_NULL_PRODUCT_COUNT NUMBER;
    V_NEGATIVE_SALES_COUNT NUMBER;
    V_FUTURE_DATE_COUNT NUMBER;
BEGIN



    -- Null Customer
    SELECT COUNT(*)
    INTO V_NULL_CUSTOMER_COUNT
    FROM RETAIL_SALES
    WHERE CUSTOMER_ID IS NULL;

    -- Null Product
    SELECT COUNT(*)
    INTO V_NULL_PRODUCT_COUNT
    FROM RETAIL_SALES
    WHERE PRODUCT_ID IS NULL;

    -- Negative Sales
    SELECT COUNT(*)
    INTO V_NEGATIVE_SALES_COUNT
    FROM RETAIL_SALES
    WHERE SALES < 0;

    SELECT COUNT(*)
    INTO V_FUTURE_DATE_COUNT
FROM RETAIL_SALES
WHERE ORDER_DATE > CURRENT_DATE();

    IF (V_NULL_CUSTOMER_COUNT > 0) THEN
    RETURN ''Validation Failed - Null Customer ID Found'';
END IF;

IF (V_NULL_PRODUCT_COUNT > 0) THEN
    RETURN ''Validation Failed - Null Product ID Found'';
END IF;

IF (V_NEGATIVE_SALES_COUNT > 0) THEN
    RETURN ''Validation Failed - Negative Sales Found'';
END IF;

IF (V_FUTURE_DATE_COUNT > 0) THEN
    RETURN ''Validation Failed - Future Order Date Found'';
END IF;


    RETURN ''Validation Successful'';

END;
';
